### ISSUE TITLE
cannot find the pin or bit for coins.

### ISSUE THREAD

**Issue by crazyjojo0251** [aostanin/saturnjvs#1]
how can I make a coin?

**Comment by aostanin** [comment]
I never looked into it since I always set games to free play.

I think you need to edit this: https://github.com/aostanin/saturnjvs/blob/master/naomi_io/JVS.cpp#L259-L260

Those two bytes have this meaning:

<table>
    <tr>
        <th/>
        <th>bit7</th>
        <th>bit6</th>
        <th>bit5</th>
        <th>bit4</th>
        <th>bit3</th>
        <th>bit2</th>
        <th>bit1</th>
        <th>bit0</th>
    </tr>
    <tr>
        <td>byte1</td>
        <td colspan="4">Slot condition</td>
        <td colspan="4">Coin count (bit13~8)</td>
    </tr>
    <tr>
        <td>byte2</td>
        <td colspan="8">Coin count (bit7~0)</td>
    </tr>
</table>​

Where the slot condition is

 | Condition Code | Meaning |
| --- | --- |
| 0 | Normal |
| 1 | Coin jammed |
| 2 | Coin counter disconnected |
| 3 | Busy |

I want to redo this project over the winter and implement more of the JVS spec.

**Comment by crazyjojo0251** [comment]
thanks for your reply,I will have a check for it.
There are somethings I can tell u with the JVS since I made an  PCB with openjvs,so you can notice these point while update your project.
1.the 485 module from different manufactures maybe  not as good as the same,
2.if Naomi donot get the response from IO it will loop again,so when them communicate success， the IO node shows a big number.
3.if add XY analogs for FPS games,the analog bit must be a stranger value and the coin bit enable in games.
4.if add analogs for driving games, many of them cannot get enough keys, such as 18 wheels.

Hope you can make a batter JVS.

**Comment by aostanin** [comment]
Thank you! I ran into problem #2 myself when I originally tried to implement this on a Raspberry Pi. The Naomi needs the address setting ACK within 1 mS. Still haven't played around with analog but I'm sure your tips will come in handy.

By the way, do you know the official JVS spec document (http://superusr.free.fr/arcade/JVS/JVST_VER3.pdf)? It's in Japanese but I'd be happy to translate any of it if necessary. I saw there there are some partial translations of it floating around (ex. https://github.com/TheOnlyJoey/openjvs/wiki/Command-details).

I'll close this for now.

**Comment by crazyjojo0251** [comment]
The version in your link is the same one I used,most useful information is already listed in OPENJVS wiki,the other are about format of analog and keyboard  ,if you need translations for some command just send me a list,I will photo my notes to you,that maybe help.

And I test the coin part in your program,some games ignore the count of coinbank after reset,so the credit always shows 0 unless get one new coin,lock the coinbank to 8000 donot work for them,the coin bit is necessary.
